[package]
name = "cli_todo"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
clap = { version = "4", features = ["derive"] }
rusqlite = { version = "0.38.0", features = ["bundled"] }
